controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\forms\ForgetPassword;
use app\models\forms\ResetPasswordForm;
use app\models\forms\SignupForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\forms\LoginForm;
use yii\helpers\Html;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Для изменения пароля
     * @return array
     */
    public function actionResetPassword()
    {
        $request = Yii::$app->request;
        $user = Yii::$app->user->identity;
        $model = new ResetPasswordForm(['uid' => $user->id]);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet) {
                return [
                    'title' => "Сменить пароль",
                    'content' => $this->renderAjax('reset-password-form', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-white pull-left btn-sm', 'data-dismiss' => "modal"]) .
                        Html::button('Изменить', ['class' => 'btn btn-primary btn-sm', 'type' => "submit"])

                ];
            } else if($model->load($request->post()) && $model->resetPassword()){
                Yii::$app->user->logout();
                return [
                    'title' => "Сменить пароль",
                    'content' => '<span class="text-success">Ваш пароль успешно изменен</span>',
                    'footer' => Html::button('Закрыть', ['class' => 'btn btn-white btn-sm', 'data-dismiss' => "modal"]),
                ];
            } else {
                return [
                    'title' => "Сменить пароль",
                    'content' => $this->renderAjax('reset-password-form', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-white pull-left btn-sm', 'data-dismiss' => "modal"]) .
                        Html::button('Изменить', ['class' => 'btn btn-primary btn-sm', 'type' => "submit"])

                ];
            }
        }
    }

    public function actionTest()
    {
//            $result = Yii::$app->mailer->compose()
//    ->setFrom('medichi.notifications@mail.ru')
//    ->setTo('qist27000@gmail.com')
//    ->setSubject('Тема сообщения')
//    ->setTextBody('Текст сообщения')
//    ->setHtmlBody('<b>текст сообщения в формате HTML</b>')
//    ->send();

//        var_dump($result);
    }

    /**
     * @param int $id
     * @param string $hash
     * @return Response
     */
    public function actionConfirm($id, $hash)
    {
        /** @var User $user */
        $user = User::find()->where(['id' => $id, 'password_hash' => $hash])->one();

        if($user){
            $user->email_approved = 1;
            $user->save(false);
            Yii::$app->session->setFlash('success', 'Вы успешно активировали ваш аккаунт');
            return $this->redirect(['site/login']);
        }

        Yii::$app->session->setFlash('error', 'Ссылка не корректна');
        return $this->redirect(['site/login']);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            if (isset($_POST['g-recaptcha-response']) && $_POST['g-recaptcha-response']) {
              $secret = '6Ld13PgZAAAAAII8iRbQeP9wQd7DyHsc2Hikr8Gu';
              $ip = $_SERVER['REMOTE_ADDR'];
              $response = $_POST['g-recaptcha-response'];
              $rsp = file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=$secret&response=$response&remoteip=$ip");
              $arr = json_decode($rsp, TRUE);
              if ($arr['success']) {

              }
              \Yii::warning($arr, 'ReCaptcha Response');
            }

            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionForgetPassword()
    {
        $this->layout = '@app/views/layouts/main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new ForgetPassword();
        if ($model->load(Yii::$app->request->post()) && $model->sendNewPassword()) {
            Yii::$app->session->setFlash('success', 'На почту отправлен новый пароль');
            return $this->goBack();
        }
        return $this->render('forget-password', [
            'model' => $model,
        ]);
    }

    /**
     * Register action.
     *
     * @return string
     */
    public function actionRegister()
    {
        $this->layout = '@app/views/layouts/main-login.php';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Вы успешно зарегистрировались');
//            (new LoginForm(['username' => $model->email, 'password' => $model->password]))->login();

            if (isset($_POST['g-recaptcha-response']) && $_POST['g-recaptcha-response']) {
              $secret = '6Ld13PgZAAAAAII8iRbQeP9wQd7DyHsc2Hikr8Gu';
              $ip = $_SERVER['REMOTE_ADDR'];
              $response = $_POST['g-recaptcha-response'];
              $rsp = file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=$secret&response=$response&remoteip=$ip");
              $arr = json_decode($rsp, TRUE);
              if ($arr['success']) {

              }
              \Yii::warning($arr, 'ReCaptcha Response');
            }

            Yii::$app->session->setFlash('success', 'Письмо активации аккаунта было отправлено на почту');

            return $this->redirect(['site/login']);
        }
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionSendLoginSms($username)
    {
        $code = rand(1000, 9999);

        \Yii::warning($code, 'Confirm code');

        $user = User::find()->where(['login' => $username])->one();

        if($user){
//            $dataQuery = http_build_query([
//                'api_id' => 'F4768781-AF07-901E-D381-B8158462E570',
//                'to' => $user->phone,
//                'msg' => "Ваш код подтверждения: {$code}",
//                'json' => '1',
//            ]);
//            $smsResponse = json_decode(file_get_contents("https://sms.ru/sms/send?{$dataQuery}"), true);

            Yii::$app->mailer->compose()
                ->setFrom('medichi.notifications@mail.ru')
                ->setTo($user->login)
                ->setSubject('Код подтверждения')
                ->setHtmlBody("Ваш код подтверждения: {$code}")
                ->send();

//            \Yii::warning($smsResponse);

            $user->confirm_code = $code;
            $user->save(false);
        }
    }

    public function actionSendSms($email)
    {
        $code = rand(1000, 9999);
        \Yii::warning($code, 'Confirm code');

//        $dataQuery = http_build_query([
//            'api_id' => 'F4768781-AF07-901E-D381-B8158462E570',
//            'to' => $phone,
//            'msg' => "Ваш код подтверждения: {$code}",
//            'json' => '1',
//        ]);
//        $smsResponse = json_decode(file_get_contents("https://sms.ru/sms/send?{$dataQuery}"), true);

//        \Yii::warning($smsResponse);

        Yii::$app->mailer->compose()
            ->setFrom('medichi.notifications@mail.ru')
            ->setTo($email)
            ->setSubject('Код подтверждения')
            ->setHtmlBody("Ваш код подтверждения: {$code}")
            ->send();

        Yii::$app->session->set('confirm_code', $code);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <!-- begin error -->
    <div class="error">
        <div class="error-code m-b-10"><?=$exception->statusCode?> <i class="fa fa-warning"></i></div>
        <div class="error-content">
            <div class="error-message"><?=$message?></div>
            <div class="error-desc m-b-20">
                Если это ошибка сервера. <br>
                Свяжитесь с тех поддержкой.
            </div>
            <div>
                <a href="/" class="btn btn-success">На главную</a>
            </div>
        </div>
    </div>
    <!-- end error -->

</div>

views/site/forget-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\forms\ForgetPassword */

$this->title = 'Востановить пароль';

$fieldOptions1 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];
?>

<div class="card card-authentication1 mx-auto my-5">
    <div class="card-body">
        <div class="card-content p-2">
            <div class="text-center">
                <img src="/img/logo.png" alt="logo icon">
            </div>
            <div class="card-title text-uppercase text-center py-3">Востановить пароль</div>
            <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
            <?= $form
                ->field($model, 'email', $fieldOptions1)
                ->label(false)
                ->textInput(['placeholder' => $model->getAttributeLabel('email'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
            <div class="login-buttons">
                <?= Html::submitButton('Востановить пароль', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Worker';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Авторизация';

$fieldOptions1 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];
?>

<div class="card card-authentication1 mx-auto my-5">
    <div class="card-body">
        <div class="card-content p-2">
            <div class="text-center">
                <img src="/img/logo.png" alt="logo icon">
            </div>
            <div class="card-title text-uppercase text-center py-3">Войти</div>
            <?php if(Yii::$app->session->hasFlash('success')): ?>
                <p class="text-success"><?= Yii::$app->session->getFlash('success') ?></p>
            <?php endif; ?>
            <?php if(Yii::$app->session->hasFlash('error')): ?>
                <p class="text-danger"><?= Yii::$app->session->getFlash('error') ?></p>
            <?php endif; ?>
            <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
            <?= $form
                ->field($model, 'username', $fieldOptions1)
                ->label(false)
                ->textInput(['placeholder' => $model->getAttributeLabel('email'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
            <?= $form
                ->field($model, 'password', $fieldOptions2)
                ->label(false)
                ->passwordInput(['placeholder' => $model->getAttributeLabel('password'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
            <div class="row">
                <div class="col-md-12">
                    <!-- добавление элемента div -->
                    <div class="g-recaptcha" data-sitekey="6LdqyAAaAAAAABzixqd18lqfoxW-4EiFbLAZRAft"></div>

                    <!-- элемент для вывода ошибок -->
                    <div class="text-danger" id="recaptchaError"></div>
                </div>
            </div>
            <div class="login-buttons" style="margin-top: 10px;">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
    <div class="card-footer text-center py-3">
        <p class="mb-0"><?= Html::a('Востановить пароль', ['site/forget-password'], ['class' => 'pull-left']) ?> <?= Html::a('Зарегистрироваться', ['site/register'], ['class' => 'pull-right']) ?></p>
    </div>
</div>



<?php

$script = <<< JS

$('#sms-button').click(function(event){
    event.preventDefault();
    var username = $('#loginform-username').val();

    var btn = this;
    
    $.get('/site/send-login-sms?username='+username, function(response){
        alert('Код отправлен');
        $('#phone-wrapper').removeClass('col-md-7');
        $('#phone-wrapper').addClass('col-md-12');
        $('#sms-wrapper').addClass('hidden');
    });
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Регистрация';

$fieldOptions1 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];

$ref = null;
if(isset($_GET['ref_id'])){
//    $ref = \app\models\RefAgent::findOne($_GET['ref_id']);
    $ref = $_GET['ref_id'];
}

if($ref){
//    $model->email = $ref->email;
    $model->ref_id = $ref;
}


?>

<div class="card card-authentication1 mx-auto my-5">
    <div class="card-body">
        <div class="card-content p-2">
            <div class="text-center">
                <img src="/img/logo.png" alt="logo icon">
            </div>
            <div class="card-title text-uppercase text-center py-3">Зарегистрироваться</div>
            <?php $form = ActiveForm::begin(['id' => 'register-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form
                        ->field($model, 'email', $fieldOptions1)
                        ->label(false)
                        ->textInput(['placeholder' => $model->getAttributeLabel('email'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
                </div>
            </div>
            <div class="row">
                <div id="phone-wrapper" class="col-md-12">
                    <?= $form
                        ->field($model, 'phone', $fieldOptions1)
                        ->label(false)
                        ->textInput(['placeholder' => $model->getAttributeLabel('phone'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
                </div>
            </div>
            <?= $form
                ->field($model, 'password', $fieldOptions2)
                ->label(false)
                ->passwordInput(['placeholder' => $model->getAttributeLabel('password'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
            <?= $form
                ->field($model, 'repeatPassword', $fieldOptions2)
                ->label(false)
                ->passwordInput(['placeholder' => $model->getAttributeLabel('repeatPassword'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
            <div class="hidden">
                <?= $form->field($model, 'ref_id')->hiddenInput()->label(false) ?>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- добавление элемента div -->
                    <div class="g-recaptcha" data-sitekey="6LdqyAAaAAAAABzixqd18lqfoxW-4EiFbLAZRAft"></div>

                    <!-- элемент для вывода ошибок -->
                    <div class="text-danger" id="recaptchaError"></div>
                </div>
            </div>
            <div class="login-buttons">
                <?= Html::submitButton('Регистрация', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>



<?php

$script = <<< JS

$('#sms-button').click(function(event){
    event.preventDefault();
    var email = $('#signupform-email').val();

    var btn = this;
    
    $.get('/site/send-sms?email='+email, function(response){
        alert('Код отправлен');
        $('#phone-wrapper').removeClass('col-md-7');
        $('#phone-wrapper').addClass('col-md-12');
        $('#sms-wrapper').addClass('hidden');
    });
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>

views/site/reset-password-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\forms\ResetPasswordForm */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'oldPassword') ?>
<?= $form->field($model, 'newPassword') ?>
<?= $form->field($model, 'repeatPassword') ?>

<?php if(!Yii::$app->request->isAjax): ?>
    <div class="form-group">
        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
    </div>
<?php endif; ?>

<?php ActiveForm::end(); ?>